---
- name: clickhouse
  src: https://github.com/zhelanovalex/Clickhouse_role
  scm: git
  version: main
- name: vector
  src: https://github.com/zhelanovalex/Vector_role
  scm: git
  version: main
- name: lighthouse
  src: https://github.com/zhelanovalex/Lighthouse_role 
  scm: git
  version: main
