---
- name: Get distrib
  become: true
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
    dest: "./vector-{{ vector_version }}-1.x86_64.rpm"
    mode: 0644
- name: Install Vector
  become: true
  ansible.builtin.yum:
    name:
      - vector-{{ vector_version }}-1.x86_64.rpm
    state: present
- name: Create config
  ansible.builtin.template:
    src: vector.conf.j2
    dest: /etc/vector/vector.yaml
    mode: 0644
    validate: vector validate --no-environment --config-yaml %s
  become: true
  notify: Start vector service
- name: Vector | Create systed unit
  ansible.builtin.template:
    src: vector.service.j2
    dest: /etc/systemd/system/vector.service
  become: true
- name: Start Vector service
  become: true
  ansible.builtin.systemd:
    name: vector
    state: started
    daemon_reload: true

