---
clickhouse_packages:
  - clickhouse-client
  - clickhouse-server
  - clickhouse-common-static
clickhouse_tablename: logs_table
clickhouse_dbname: logs
clickhouse_user: vectneto
clickhouse_password: vectneto
clickhouse_config_path: /etc/clickhouse-server/config.xml
clickhouse_users_path: /etc/clickhouse-server/users.xml

